spring:
  application:
    name: rabbit-producer
  rabbitmq:
    host: ${RABBIT_HOST:172.104.150.159}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:devfest}
    password: ${RABBIT_PASSWORD:devfestbaku2024}
